version: '3.4'

services:
  hruknihohlinabot:
    image: ${DOCKER_REGISTRY-}hruknihohlinabot
    container_name: hruknihohlinabot
    build:
      context: .
      dockerfile: ConsoleApp1/Dockerfile
    environment:
      # - ConnectionStrings__DefaultConnection=User ID=postgres;Password=postgres;Server=hrukni_database;Port=5432;Database=HrukniHohlinaBotDB; IntegratedSecurity=true;Pooling=true;
      # - ConnectionStrings__DefaultConnection=Username=postgres;Password=postgres;Server=hrukni_database;Port=5432;Database=HrukniHohlinaBotDB;Pooling=true;
      # - ConnectionStrings__DefaultConnection=Username=postgres;Password=postgres;Host=localhost;Port=5432;Database=HrukniHohlinaBotDB;Pooling=true;
      - ConnectionStrings__DefaultConnection=Username=postgres;Password=postgres;Host=hrukni_database;Port=5432;Database=HrukniHohlinaBotDB;Pooling=true;
    # ports:
    #   - "5000:5000"
    #   - "5001:5001"
    depends_on:
      - hrukni_database
    networks:
      - hrukni_network

  hrukni_database:
    image: postgres:latest  
    container_name: hrukni_database
    environment:
        - POSTGRES_DB=HrukniHohlinaBotDB
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    volumes:
        - app_data:/var/lib/postgresql/data
        # - app_data:/var/lib/backup/data
        # - ./.containers/hrukni_database:/var/lib/postgresql/data
        # - ./.containers/hrukni_database:/var/lib/backup/data
    ports: 
        - 5432:5432
    networks:
      - hrukni_network
      
volumes:
    app_data:  

networks:
  hrukni_network:
    driver: bridge
  
  