version: '3.4'

services:
  hruknihohlinabot:
    image: ${DOCKER_REGISTRY-}hruknihohlinabot
    container_name: hruknihohlinabot
    build:
      context: .
      dockerfile: ConsoleApp1/Dockerfile
    environment:
      - TZ=Europe/Kyiv
      - ConnectionStrings__DefaultConnection=Username=postgres;Password=postgres;Host=hrukni_database;Port=5432;Database=HrukniHohlinaBotDB;Pooling=true;
    depends_on:
      - hrukni_database
    networks:
      - hrukni_network

  hrukni_database:
    image: postgres:latest  
    container_name: hrukni_database
    environment:
        - POSTGRES_DB=HrukniHohlinaBotDB
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    volumes:
        - app_data:/var/lib/postgresql/data
    ports: 
        - 5432:5432
    networks:
      - hrukni_network
      
volumes:
    app_data:  

networks:
  hrukni_network:
    driver: bridge
  
  